burgershop/config/routes.rb
Rails.application.routes.draw do
  resources :burgers
  get 'home/index'

  root 'home#index'

end

burgershop/app/models/burger.rb
class Burger < ActiveRecord::Base
end

burgershop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

burgershop/app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: [:show, :edit, :update, :destroy]

  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1
  # PATCH/PUT /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger.destroy
    respond_to do |format|
      format.html { redirect_to burgers_url, notice: 'Burger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def burger_params
      params.require(:burger).permit(:name, :price, :description)
    end
end

burgershop/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

burgershop/app/helpers/application_helper.rb
module ApplicationHelper
end

burgershop/app/helpers/burgers_helper.rb
module BurgersHelper
end

burgershop/app/helpers/home_helper.rb
module HomeHelper
end

burgershop/app/views/burgers/_form.html.erb
<%= form_for(@burger) do |f| %>
  <% if @burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
      <% @burger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

burgershop/app/views/burgers/edit.html.erb
<h1>Editing Burger</h1>

<%= render 'form' %>

<%= link_to 'Show', @burger %> |
<%= link_to 'Back', burgers_path %>

burgershop/app/views/burgers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Burgers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @burgers.each do |burger| %>
      <tr>
        <td><%= burger.name %></td>
        <td><%= burger.price %></td>
        <td><%= burger.description %></td>
        <td><%= link_to 'Show', burger %></td>
        <td><%= link_to 'Edit', edit_burger_path(burger) %></td>
        <td><%= link_to 'Destroy', burger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Burger', new_burger_path, class: 'btn btn-primary' %>

burgershop/app/views/burgers/new.html.erb
<h1>New Burger</h1>

<%= render 'form' %>

<%= link_to 'Back', burgers_path %>

burgershop/app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @burger.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @burger.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @burger.description %>
</p>

<%= link_to 'Edit', edit_burger_path(@burger) %> |
<%= link_to 'Back', burgers_path %>

burgershop/app/views/home/index.html.erb
<h1>Welcome to The Burger Shop</h1>
<p>Check out our burger selection, updated every week!</p>

<a href="/burgers">Weeks Burger list</a>

burgershop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

    <title>Burgershop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

<div class="container">
    <%= yield %>
</div>

</body>
</html>